services:
  donetick:
    image: docker.io/donetick/donetick
    restart: unless-stopped
    #ports:
    #  - 2021:2021
    volumes:
      - ./data/donetick:/donetick-data:z
      - ./config/donetick:/config:z
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db

  spliit:
    build:
      context: ./dockerfiles/spliit
    restart: unless-stopped
    #ports:
    #  - 3000:3000
    env_file:
      - ./config/postgres/postgres.env
      - ./config/spliit/spliit.env
    depends_on:
      - postgres

  postgres:
    image: docker.io/library/postgres:17
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z
    env_file:
      - ./config/postgres/postgres.env

  certbot:
    build: ./dockerfiles/certbot
    restart: always
    container_name: auto_cert_renewal
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt:z
      - ./data/www/certbot:/var/www/certbot:z
    depends_on:
      - nginx

  nginx:
    build:
      context: ./dockerfiles/nginx
    restart: unless-stopped
    volumes:
      - ./data/www/certbot:/var/www/certbot:ro
      - ./static:/var/www/html:ro
      - ./data/letsencrypt:/etc/letsencrypt:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/config.d:/etc/nginx/config.d:ro

    ports:
      - 80:80
      - 443:443
    depends_on:
      - spliit
      - donetick


