#!/usr/bin/env sh

set -euxo pipefail

cat <<EOF > .env
# db
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_PRISMA_URL=${POSTGRES_PRISMA_URL}
POSTGRES_URL_NON_POOLING=${POSTGRES_URL_NON_POOLING}
# app-minio
NEXT_PUBLIC_ENABLE_EXPENSE_DOCUMENTS=${SPLIT_NEXT_PUBLIC_ENABLE_EXPENSE_DOCUMENTS}
S3_UPLOAD_KEY=${SPLIT_S3_UPLOAD_KEY}
S3_UPLOAD_SECRET=${SPLIT_S3_UPLOAD_SECRET}
S3_UPLOAD_BUCKET=${SPLIT_S3_UPLOAD_BUCKET}
S3_UPLOAD_REGION=${SPLIT_S3_UPLOAD_REGION}
S3_UPLOAD_ENDPOINT=${SPLIT_S3_UPLOAD_ENDPOINT}
# app-openai
NEXT_PUBLIC_ENABLE_RECEIPT_EXTRACT=${SPLIT_NEXT_PUBLIC_ENABLE_RECEIPT_EXTRACT}
OPENAI_API_KEY=${SPLIT_OPENAI_API_KEY}
NEXT_PUBLIC_ENABLE_CATEGORY_EXTRACT=${SPLIT_NEXT_PUBLIC_ENABLE_CATEGORY_EXTRACT}
EOF

npx prisma migrate deploy
npm run start

